theme: jekyll-theme-slate
title: Sai Machiraju's Portfolio
description: A centralized location to find my articles, programming projects, and perspectives.
baseurl: /saimachi.github.io
github:
  is_project_page: false